name: build-react
on: [push]
jobs:
  build-react:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: latest
    - run: |
        npm i
        npm run build
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "[Bot] build react"
        branch: deploy
        create_branch: true
        push_options: '--force'
